# Generated by Django 2.2.14 on 2020-07-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='index_slider',
            fields=[
                ('slider_id', models.AutoField(primary_key=True, serialize=False)),
                ('slider_order_id', models.CharField(max_length=400)),
                ('slider_image', models.CharField(max_length=400)),
                ('slider_title', models.CharField(max_length=1000)),
                ('slider_description', models.TextField()),
            ],
        ),
    ]
