# Generated by Django 2.2.14 on 2020-07-31 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_index_slider_slider_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='index_introduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='index_people',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_pic', models.CharField(max_length=400)),
                ('tutor', models.TextField()),
                ('tutor_en', models.TextField()),
            ],
        ),
    ]
