# Generated by Django 2.2.14 on 2020-08-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_achievementss'),
    ]

    operations = [
        migrations.CreateModel(
            name='people',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.CharField(max_length=400)),
                ('name', models.CharField(max_length=400)),
                ('identity', models.CharField(max_length=400)),
                ('category', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='people_detail_simple',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
                ('identity', models.CharField(max_length=400)),
                ('major', models.CharField(max_length=400)),
                ('subject', models.CharField(max_length=400)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='achievementss',
            name='index2',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='achievementss',
            name='index3',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='achievementss',
            name='index_link2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='achievementss',
            name='index_link3',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
