# Generated by Django 3.1.1 on 2020-10-18 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_people_education_peradmin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Peradmin',
            new_name='Peradminuse',
        ),
    ]
